In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg

### Практическое задание №5


5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.


5.2.
Вычислите определитель:
[[1, 2, 3], [4, 0, 6], [7, 8, 9]]


In [2]:
D = 1 * (0 * 9 - 8 * 6) + 2 * (4 * 9 - 7 * 6) + 3 * (4 * 8 - 7 * 0)
print('определитель матрицы: [[1, 2, 3], [4, 0, 6], [7, 8, 9]] равен ', D)

определитель матрицы: [[1, 2, 3], [4, 0, 6], [7, 8, 9]] равен  36


In [3]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])

In [4]:
print('определитель матрицы: [[1, 2, 3], [4, 0, 6], [7, 8, 9]] равен %0.2f' % (np.linalg.det(A)))

определитель матрицы: [[1, 2, 3], [4, 0, 6], [7, 8, 9]] равен 60.00


5.3.
1. Вычислите матрицу, обратную данной: [[1, 2, 3], [4, 0, 6], [7, 8, 9]]


In [5]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])

In [6]:
print('обратная матрица от  [[1, 2, 3], [4, 0, 6], [7, 8, 9]] равна:\n', (np.linalg.inv(A)))

обратная матрица от  [[1, 2, 3], [4, 0, 6], [7, 8, 9]] равна:
 [[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


2. Приведите пример матрицы 4х4, ранг которой равен 1.


In [7]:
C = np.array([[1, -1, 2, 1], [0, 0, 0, 0], [0, 0, 0, 0 ], [0, 0, 0, 0]])

In [8]:
print('ранг матрицы от  [[1, 2, 3], [4, 0, 6], [7, 8, 9]] равен:\n', (np.linalg.matrix_rank(C)))

ранг матрицы от  [[1, 2, 3], [4, 0, 6], [7, 8, 9]] равен:
 1


5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

In [9]:
print(' скалярное произведение двух векторов (1, 5)  и  (2, 8) равно:\n', (1 * 2 + 5 * 8))

 скалярное произведение двух векторов (1, 5)  и  (2, 8) равно:
 42


5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


In [10]:
# Смешанное произведение векторов равно определителю матрицы, составленной из этих векторов.
C = np.array([[1, 5, 0], [2, 8, 7], [7, 1.5, 3]])

In [11]:
print('Вычислите смешанное произведение трех векторов: ((1, 5, 0), (2, 8, 7) и (7, 1.5, 3)) равна %0.2f' % (np.linalg.det(C)))

Вычислите смешанное произведение трех векторов: ((1, 5, 0), (2, 8, 7) и (7, 1.5, 3)) равна 228.50


### Практическое задание №6


1. Решите линейную систему:


In [12]:
M1 = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
V1 = np.array([12, 2, 1])

In [13]:
np.linalg.solve(M1, V1)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15


In [14]:
M2 = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
V2 = np.array([1, 7, 12, 7, 15])

In [15]:
R2 = np.linalg.lstsq(M2, V2)
R2

C:\Users\biser1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [16]:
print('Псевдорешение СЛАУ:x + 2y – z = 1 3x – 4y = 7 8x – 5y + 2z = 12 2x – 5z = 7 11x +4y – 7z = 15\nравно =  ', R2[0])

Псевдорешение СЛАУ:x + 2y – z = 1 3x – 4y = 7 8x – 5y + 2z = 12 2x – 5z = 7 11x +4y – 7z = 15
равно =   [ 1.13919353 -0.90498444 -0.9009803 ]


3. Сколько решений имеет линейная система:


In [17]:
M3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
V3 = np.array([12, 2, 1])

In [18]:
def determinant(M):
    if abs(round(np.linalg.det(M))) == 0:
        print('Система уравнений вырожденная')
    else:
        print('Система уравений имеет решение')

In [19]:
determinant(M3)

Система уравнений вырожденная


In [20]:
# Изменим вектор правой части, чтобы система стала совместной
M4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
V4 = np.array([[12, 24, 36]])

In [21]:
C4 = np.concatenate((M4, V4.T), axis=1)
C4

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 24],
       [ 7,  8,  9, 36]])

In [22]:
np.linalg.matrix_rank(M4, 0.0001), np.linalg.matrix_rank(C4, 0.0001)

(2, 2)

4. Вычислите LU-разложение матрицы:

После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.


In [23]:
M5 = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])

In [24]:
P, L, U = scipy.linalg.lu(M5)
print('P', P)
print('L', L)
print('U', U)

P [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [25]:
# Вектор правой части
V5 = np.array([12, 45, 33])

In [26]:
y = np.linalg.solve(L, V5)

In [27]:
x = np.linalg.solve(U, y)

In [28]:
print('Решение СЛАУ ', x)

Решение СЛАУ  [55.51388889 -2.21527778 -2.02777778]


5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 


In [29]:
M6 = np.array([[1, 2, -1], [8, -5, 2]])
V6 = np.array([1, 12])

6. Найдите одно из псевдорешений вырожденной системы:

Попробуйте также отыскать и нормальное псевдорешение.
