In [81]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg

### Практическое задание №6


1. Решите линейную систему:


In [4]:
M1 = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
V1 = np.array([12, 2, 1])

In [5]:
np.linalg.solve(M1, V1)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15


In [6]:
M2 = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
V2 = np.array([1, 7, 12, 7, 15])

In [10]:
R2 = np.linalg.lstsq(M2, V2)
R2

C:\Users\Xiaomi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [16]:
print('Псевдорешение СЛАУ:x + 2y – z = 1 3x – 4y = 7 8x – 5y + 2z = 12 2x – 5z = 7 11x +4y – 7z = 15\nравно =  ', R2[0])

Псевдорешение СЛАУ:x + 2y – z = 1 3x – 4y = 7 8x – 5y + 2z = 12 2x – 5z = 7 11x +4y – 7z = 15
равно =   [ 1.13919353 -0.90498444 -0.9009803 ]


3. Сколько решений имеет линейная система:


In [61]:
M3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
V3 = np.array([12, 2, 1])

In [50]:
def determinant(M):
    if abs(round(np.linalg.det(M))) == 0:
        print('Система уравнений вырожденная')
    else:
        print('Система уравений имеет решение')

In [62]:
determinant(M3)

Система уравнений вырожденная


In [72]:
# Изменим вектор правой части, чтобы система стала совместной
M4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
V4 = np.array([[12, 24, 36]])

In [73]:
C4 = np.concatenate((M4, V4.T), axis=1)
C4

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 24],
       [ 7,  8,  9, 36]])

In [74]:
np.linalg.matrix_rank(M4, 0.0001), np.linalg.matrix_rank(C4, 0.0001)

(2, 2)

4. Вычислите LU-разложение матрицы:

После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.


In [77]:
M5 = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])

In [83]:
P, L, U = scipy.linalg.lu(M5)
print('P', P)
print('L', L)
print('U', U)

P [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [177]:
# Вектор правой части
V5 = np.array([12, 45, 33])

In [210]:
y = np.linalg.solve(L, V5)

In [211]:
x = np.linalg.solve(U, y)

In [212]:
print('Решение СЛАУ ', x)

Решение СЛАУ  [55.51388889 -2.21527778 -2.02777778]


5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 


In [213]:
M6 = np.array([[1, 2, -1], [8, -5, 2]])
V6 = np.array([1, 12])

6. Найдите одно из псевдорешений вырожденной системы:

Попробуйте также отыскать и нормальное псевдорешение.
